[profile.default]
src = 'src'
script = 'script'
out = 'out'
libs = ['lib']

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config